In [2]:
import numpy as np

In [3]:
a=[1,2,3]

In [4]:
m=np.ndarray(a)

In [5]:
d=np.ones((4,3))

In [6]:
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print(m)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [11]:
print(m.shape[0])

1


In [13]:
print(d.shape[0])

4


In [14]:
print(d.shape[1])

3


In [17]:
print(d.size)

12


In [21]:
def inizilisation(m,n):
    x=np.random.rand(m,n)
    print(x)



In [22]:
inizilisation(5,3)

[[0.50143505 0.65735777 0.31517525]
 [0.05519238 0.0875396  0.51509178]
 [0.44036282 0.76245908 0.89110048]
 [0.90099874 0.55391653 0.10489744]
 [0.1598907  0.64328021 0.05869872]]


In [39]:
a = np.array([[1,2],[3,4]])

In [27]:
print(a)

[[1 2]
 [3 4]]


In [41]:
b=np.array([[7,8]])

In [29]:
print(b)

[7 8]


In [30]:
a.T

array([[1, 3],
       [2, 4]])

In [42]:
c= np.concatenate((a,b),axis=0)

In [34]:
a.shape


(2, 2)

In [35]:
b.shape

(2,)

In [36]:
b.T.shape

(2,)

In [44]:
c= np.concatenate((a,b.T),axis=1)